[2025-01-10T14:27:33.276+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prepare_churn_dataset.create_table_task manual__2025-01-10T14:27:31.342234+00:00 [queued]>
[2025-01-10T14:27:33.284+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prepare_churn_dataset.create_table_task manual__2025-01-10T14:27:31.342234+00:00 [queued]>
[2025-01-10T14:27:33.285+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-01-10T14:27:33.305+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): create_table_task> on 2025-01-10 14:27:31.342234+00:00
[2025-01-10T14:27:33.312+0000] {standard_task_runner.py:57} INFO - Started process 166 to run task
[2025-01-10T14:27:33.315+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'prepare_churn_dataset', 'create_table_task', 'manual__2025-01-10T14:27:31.342234+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/churn.py', '--cfg-path', '/tmp/tmpstazc5ob']
[2025-01-10T14:27:33.316+0000] {standard_task_runner.py:85} INFO - Job 28: Subtask create_table_task
[2025-01-10T14:27:33.358+0000] {task_command.py:416} INFO - Running <TaskInstance: prepare_churn_dataset.create_table_task manual__2025-01-10T14:27:31.342234+00:00 [running]> on host 6c2c8705fe78
[2025-01-10T14:27:33.437+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='prepare_churn_dataset' AIRFLOW_CTX_TASK_ID='create_table_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-10T14:27:31.342234+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-10T14:27:31.342234+00:00'
[2025-01-10T14:27:33.442+0000] {base.py:73} INFO - Using connection ID 'destination_db' for task execution.
[2025-01-10T14:27:34.016+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-01-10T14:27:34.025+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_churn_dataset, task_id=create_table_task, execution_date=20250110T142731, start_date=20250110T142733, end_date=20250110T142734
[2025-01-10T14:27:34.057+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-01-10T14:27:34.072+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
