[2025-01-30T06:11:12.365+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-30T06:11:12.382+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prepare_churn_dataset.create_table_task manual__2025-01-30T06:11:09.552302+00:00 [queued]>
[2025-01-30T06:11:12.389+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prepare_churn_dataset.create_table_task manual__2025-01-30T06:11:09.552302+00:00 [queued]>
[2025-01-30T06:11:12.390+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-30T06:11:12.401+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): create_table_task> on 2025-01-30 06:11:09.552302+00:00
[2025-01-30T06:11:12.411+0000] {standard_task_runner.py:72} INFO - Started process 159 to run task
[2025-01-30T06:11:12.425+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'prepare_churn_dataset', 'create_table_task', 'manual__2025-01-30T06:11:09.552302+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/churn.py', '--cfg-path', '/tmp/tmpxxd3kcdu']
[2025-01-30T06:11:12.426+0000] {standard_task_runner.py:105} INFO - Job 40: Subtask create_table_task
[2025-01-30T06:11:12.514+0000] {task_command.py:467} INFO - Running <TaskInstance: prepare_churn_dataset.create_table_task manual__2025-01-30T06:11:09.552302+00:00 [running]> on host 0be31ceb717f
[2025-01-30T06:11:12.620+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='prepare_churn_dataset' AIRFLOW_CTX_TASK_ID='create_table_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-30T06:11:09.552302+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-30T06:11:09.552302+00:00'
[2025-01-30T06:11:12.621+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-30T06:11:12.622+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-30T06:11:12.623+0000] {logging_mixin.py:190} INFO - Current task name:create_table_task state:running start_date:2025-01-30 06:11:12.383469+00:00
[2025-01-30T06:11:12.623+0000] {logging_mixin.py:190} INFO - Dag name:prepare_churn_dataset and current dag run status:running
[2025-01-30T06:11:12.623+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-30T06:11:12.632+0000] {base.py:84} INFO - Retrieving connection 'destination_db'
[2025-01-30T06:11:12.633+0000] {sql.py:186} WARNING - This setter is for backward compatibility and should not be used.
Since the introduction of connection property, the providers listed below breaks due to assigning value to self.connection in their __init__ method.
* apache-***-providers-mysql<5.7.1
* apache-***-providers-elasticsearch<5.5.1
* apache-***-providers-postgres<5.13.0
[2025-01-30T06:11:12.638+0000] {base.py:84} INFO - Retrieving connection 'destination_db'
[2025-01-30T06:11:13.085+0000] {churn.py:61} INFO - Таблица users_churn уже существует.
[2025-01-30T06:11:13.087+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-30T06:11:13.100+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-30T06:11:13.101+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=prepare_churn_dataset, task_id=create_table_task, run_id=manual__2025-01-30T06:11:09.552302+00:00, execution_date=20250130T061109, start_date=20250130T061112, end_date=20250130T061113
[2025-01-30T06:11:13.109+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-30T06:11:13.110+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-30T06:11:13.110+0000] {logging_mixin.py:190} INFO - Dag name:prepare_churn_dataset queued_at:2025-01-30 06:11:09.574344+00:00
[2025-01-30T06:11:13.111+0000] {logging_mixin.py:190} INFO - Task hostname:0be31ceb717f operator:_PythonDecoratedOperator
[2025-01-30T06:11:13.159+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-30T06:11:13.181+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-30T06:11:13.182+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
